name: shiftleft-scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
       type: "credscan,java,depscan"

